Spatial Interaction Models

* 1
explain the different models briefly, 
** unconstrained
amount of flow between pair of nodes iand j is a simple function of their calculated "mass" attributes and the calculated "distance" 
flow between two nodes can be any value less than the total flow of the system
** production constrained
flow between two nodes can be any value up to the total current flow from the origin node
** attraction constrained
flow between two nodes can be any value up to the current total flow into the destination node 
** doubly constrained
the sums  must be less than the max so total in flows and out flows of each location do not change. 

which situations would each be used in? 
unconstrained would be used in a model that studies 

production constrained models could be used to study a scenario where a population changes

attraction constrained models could be used to study a scenario where an employment or spending option changes


* 2
explain the role of parameters briefly
the parameters reflect the relative importance of mass for each of the two points and distance. 

* 3
select a scenario and using the practical, explore the consequences of varying some of the model parameters and inputs on both interaction flows and the origin or destination estimates produced by the model. 
